name: Secure Pipeline

on:
  pull_request:
    branches:
      - test

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  security-check:

    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install requests

      - name: Mostrar Secrets
        run: |
          python - <<EOF
          import os

          print("TOKEN EXISTE:", bool(os.environ.get("TELEGRAM_TOKEN")))
          print("CHAT_ID EXISTE:", bool(os.environ.get("TELEGRAM_CHAT_ID")))

          if os.environ.get("TELEGRAM_TOKEN"):
              print("TOKEN:", os.environ["TELEGRAM_TOKEN"][:10] + "...")

          if os.environ.get("TELEGRAM_CHAT_ID"):
              print("CHAT:", os.environ["TELEGRAM_CHAT_ID"])
          EOF

      - name: Telegram Prueba
        run: |
          python - <<EOF
          import requests
          import os

          url = f"https://api.telegram.org/bot{os.environ['TELEGRAM_TOKEN']}/sendMessage"

          r = requests.post(
              url,
              json={
                  "chat_id": os.environ["TELEGRAM_CHAT_ID"],
                  "text": "🚀 PRUEBA GITHUB ACTIONS"
              }
          )

          print("STATUS:", r.status_code)
          print("RESPUESTA:")
          print(r.text)

          EOF

      - name: Security Check
        run: |
          python src/ci_cd/security_check.py sample.c

      - name: Run Tests
        run: |
          pytest

      - name: Telegram Final
        if: success()
        run: |
          python - <<EOF
          import requests
          import os

          r = requests.post(
              f"https://api.telegram.org/bot{os.environ['TELEGRAM_TOKEN']}/sendMessage",
              json={
                  "chat_id": os.environ["TELEGRAM_CHAT_ID"],
                  "text": "✅ Pipeline completado"
              }
          )

          print(r.status_code)
          print(r.text)
          EOF